# Étape 1 : Analyse des phrases dans le fichier XML
Les fichiers .data.xml contiennent des phrases ou des contextes annotés, tandis que les fichiers .gold.key.txt associent les mots cibles à leurs sens (par exemple, des BabelNet IDs).

### Extrait des fichiers XML :
Utilisation de la bibliothèque xml.etree.ElementTree pour extraire les phrases et mots annotés :

In [1]:
# chemin dataset en français
french_data_path = r"C:\Users\pc\Downloads\BIBDA\S3\Analyse de Sentiments et Text Mining\french-data\training_datasets_fr\semcor_fr\semcor_fr.data.xml"

# chemin dataset en anglais
english_data_path = r"C:\Users\pc\Downloads\BIBDA\S3\Analyse de Sentiments et Text Mining\English-data\training_datasets_en\semcor_en\semcor_en.data.xml"

In [2]:
from google.colab import files

uploaded = files.upload()  # Cette commande ouvrira une boîte de dialogue pour télécharger vos fichiers

Saving semcor_en.data.xml to semcor_en.data.xml
Saving semcor_en.gold.key.txt to semcor_en.gold.key.txt

In [3]:
english_data_path = '/content/semcor_en.data.xml'

In [4]:
import xml.etree.ElementTree as ET

def parse_data(file_path):
    tree = ET.parse(file_path)
    root = tree.getroot()
    sentences = []

    for text in root.findall('.//text'):  # Parcourt les textes
        for sentence in text.findall('.//sentence'):  # Parcourt les phrases
            words = []
            # Ne garde que les mots annotés comme <instance>
            for instance in sentence.findall('.//instance'):  # Trouve les mots annotés "instance"
                words.append(instance.text)
            sentences.append(" ".join(words))  # Concatène les mots annotés
    return sentences

In [5]:
# Test avec le fichier XML
sentences = parse_data(english_data_path)

print(sentences[:5])  # Affiche les 5 premières phrases

['long been reviewed objectives benefit service program', 'permitted become giveaway program rather has goal improved employee morale consequently increased productivity', 'effort make assess results program', 'measure reduced absenteeism turnover accidents grievances improved quality output', 'set specific objectives employee publication']

# Étape 2 : Association des mots annotés avec leurs identifiants de sens

In [6]:
def parse_gold_keys(file_path):
    gold_keys = {}
    with open(file_path, 'r', encoding='utf-8') as file:
        for line in file:
            line = line.strip()
            if not line or line.startswith('#'):
                continue

            parts = line.split()
            if len(parts) >= 2:
                instance_id = parts[0]
                # Si plusieurs sens sont associés à l'instance, les ajouter dans une liste
                sense_ids = parts[1:]
                gold_keys[instance_id] = sense_ids
            else:
                print(f"Ligne ignorée (format incorrect): {line}")  # Affiche une ligne mal formatée
    return gold_keys

In [7]:
# Test avec le fichier gold key
gold_key_path = r"/content/semcor_en.gold.key.txt"
gold_keys = parse_gold_keys(gold_key_path)

print(list(gold_keys.items())[:5])  # Affiche les 5 premiers mappings

[('d000.s000.t000', ['bn:00106124a']), ('d000.s000.t001', ['bn:00083181v']), ('d000.s000.t002', ['bn:00092618v']), ('d000.s000.t003', ['bn:00002179n']), ('d000.s000.t004', ['bn:00009904n'])]

# Étape 3 : Associer les phrases avec leurs annotations
Nous combinons les phrases et les identifiants de sens en utilisant les informations du fichier gold key :

In [8]:
def associate_annotations(file_path, gold_keys):
    tree = ET.parse(file_path)
    root = tree.getroot()
    annotations = []

    for text in root.findall('.//text'):
        for sentence in text.findall('.//sentence'):
            sentence_id = sentence.attrib['id']  # ID de la phrase
            annotated_words = []
            for instance in sentence.findall('.//instance'):  # Parcourt les instances annotées
                instance_id = instance.attrib['id']  # ID de l'instance
                word = instance.text
                sense_id = gold_keys.get(instance_id, "unknown")  # Récupère l'identifiant de sens
                annotated_words.append((word, sense_id))
            annotations.append((sentence_id, annotated_words))
    return annotations

In [9]:
# Associer annotations
annotations = associate_annotations(english_data_path, gold_keys)

# Afficher les 5 premières annotations
for sentence_id, annotated_words in annotations[:5]:
    print(f"Sentence ID: {sentence_id}")
    for word, sense_id in annotated_words:
        print(f"  Word: {word}, Sense ID: {sense_id}")

Sentence ID: d000.s000
  Word: long, Sense ID: ['bn:00106124a']
  Word: been, Sense ID: ['bn:00083181v']
  Word: reviewed, Sense ID: ['bn:00092618v']
  Word: objectives, Sense ID: ['bn:00002179n']
  Word: benefit, Sense ID: ['bn:00009904n']
  Word: service, Sense ID: ['bn:00070654n']
  Word: program, Sense ID: ['bn:00064646n']
Sentence ID: d000.s001
  Word: permitted, Sense ID: ['bn:00082536v']
  Word: become, Sense ID: ['bn:00083294v']
  Word: giveaway, Sense ID: ['bn:00040564n']
  Word: program, Sense ID: ['bn:00064646n']
  Word: rather, Sense ID: ['bn:00115972r']
  Word: has, Sense ID: ['bn:00088078v']
  Word: goal, Sense ID: ['bn:00030721n']
  Word: improved, Sense ID: ['bn:00104710a']
  Word: employee, Sense ID: ['bn:00030618n']
  Word: morale, Sense ID: ['bn:00055852n']
  Word: consequently, Sense ID: ['bn:00114106r']
  Word: increased, Sense ID: ['bn:00104887a']
  Word: productivity, Sense ID: ['bn:00064598n']
Sentence ID: d000.s002
  Word: effort, Sense ID: ['bn:00007011n']
  Word: make, Sense ID: ['bn:00087106v']
  Word: assess, Sense ID: ['bn:00082720v']
  Word: results, Sense ID: ['bn:00034520n']
  Word: program, Sense ID: ['bn:00064646n']
Sentence ID: d000.s003
  Word: measure, Sense ID: ['bn:00082720v']
  Word: reduced, Sense ID: ['bn:00101030a']
  Word: absenteeism, Sense ID: ['bn:00000435n']
  Word: turnover, Sense ID: ['bn:00030623n']
  Word: accidents, Sense ID: ['bn:00000690n']
  Word: grievances, Sense ID: ['bn:00041786n']
  Word: improved, Sense ID: ['bn:00104711a']
  Word: quality, Sense ID: ['bn:00065538n']
  Word: output, Sense ID: ['bn:00059788n']
Sentence ID: d000.s004
  Word: set, Sense ID: ['bn:00086468v']
  Word: specific, Sense ID: ['bn:00111001a']
  Word: objectives, Sense ID: ['bn:00002179n']
  Word: employee, Sense ID: ['bn:00030618n']
  Word: publication, Sense ID: ['bn:00065106n']

In [10]:
print(len(sentences))
print(len(annotations))

37176
37176

In [11]:
for i in range(5):
    print(f"Phrase : {sentences[i]}")
    print(f"Annotations : {annotations[i]}")

Phrase : long been reviewed objectives benefit service program
Annotations : ('d000.s000', [('long', ['bn:00106124a']), ('been', ['bn:00083181v']), ('reviewed', ['bn:00092618v']), ('objectives', ['bn:00002179n']), ('benefit', ['bn:00009904n']), ('service', ['bn:00070654n']), ('program', ['bn:00064646n'])])
Phrase : permitted become giveaway program rather has goal improved employee morale consequently increased productivity
Annotations : ('d000.s001', [('permitted', ['bn:00082536v']), ('become', ['bn:00083294v']), ('giveaway', ['bn:00040564n']), ('program', ['bn:00064646n']), ('rather', ['bn:00115972r']), ('has', ['bn:00088078v']), ('goal', ['bn:00030721n']), ('improved', ['bn:00104710a']), ('employee', ['bn:00030618n']), ('morale', ['bn:00055852n']), ('consequently', ['bn:00114106r']), ('increased', ['bn:00104887a']), ('productivity', ['bn:00064598n'])])
Phrase : effort make assess results program
Annotations : ('d000.s002', [('effort', ['bn:00007011n']), ('make', ['bn:00087106v']), ('assess', ['bn:00082720v']), ('results', ['bn:00034520n']), ('program', ['bn:00064646n'])])
Phrase : measure reduced absenteeism turnover accidents grievances improved quality output
Annotations : ('d000.s003', [('measure', ['bn:00082720v']), ('reduced', ['bn:00101030a']), ('absenteeism', ['bn:00000435n']), ('turnover', ['bn:00030623n']), ('accidents', ['bn:00000690n']), ('grievances', ['bn:00041786n']), ('improved', ['bn:00104711a']), ('quality', ['bn:00065538n']), ('output', ['bn:00059788n'])])
Phrase : set specific objectives employee publication
Annotations : ('d000.s004', [('set', ['bn:00086468v']), ('specific', ['bn:00111001a']), ('objectives', ['bn:00002179n']), ('employee', ['bn:00030618n']), ('publication', ['bn:00065106n'])])

# Resultats

Extraction des données XML : Les phrases ont été correctement extraites à partir du fichier XML, en se concentrant sur les instances annotées.
Gestion des clés dorées (gold keys) : Les clés dorées (celles correspondant aux sens des mots) ont été extraites et plusieurs identifiants de sens sont gérés correctement pour une même instance.

# Prochaine étape : Désambiguïsation des mots avec un modèle Transformers
Maintenant que les données sont correctement extraites et annotées, la prochaine étape serait d'appliquer un modèle de désambiguïsation de sens (Word Sense Disambiguation - WSD) utilisant un modèle de type Transformers.

Pour cela, on peux utiliser des modèles pré-entraînés comme BERT, RoBERTa (version améliorés de BERT), ou XLM-R (version multilingue de BERT) qui sont bien adaptés pour les tâches de désambiguïsation des mots. Ces modèles sont disponibles via la bibliothèque transformers de Hugging Face.

# BERT ?

# RoBERTa ?

#### Conversion en JSON

In [12]:
import json

def export_to_json(sentences_with_annotations, output_path):
    """
    Exporte les données des phrases avec annotations dans un fichier JSON.

    :param sentences_with_annotations: Liste contenant des tuples (ID de phrase, annotations).
    :param output_path: Le chemin du fichier de sortie pour le fichier JSON.
    """
    sentences_data = []
    for sentence_data in sentences_with_annotations:
        sentence_id = sentence_data[0]  # L'ID de la phrase se trouve à l'index 0
        annotations = [
            [annotation[0], annotation[1]]  # Le mot est à l'index 0 et les sens à l'index 1
            for annotation in sentence_data[1]
        ]
        sentences_data.append([sentence_id, annotations])

    with open(output_path, 'w', encoding='utf-8') as json_file:
        json.dump(sentences_data, json_file, ensure_ascii=False, indent=4)
    print(f"Les données ont été exportées en JSON vers {output_path}")

In [ ]:
output_path_json = r"C:\Users\pc\Downloads\BIBDA\S3\Analyse de Sentiments et Text Mining\english-data\english_wsd_dataset.json"
export_to_json(annotations, output_path_json)

Les données ont été exportées en JSON vers C:\Users\pc\Downloads\BIBDA\S3\Analyse de Sentiments et Text Mining\english-data\english_wsd_dataset.json

In [13]:
from google.colab import files

uploaded = files.upload()  # Cette commande ouvrira une boîte de dialogue pour télécharger vos fichiers

Saving english_wsd_dataset.json to english_wsd_dataset.json

In [14]:
import pandas as pd
pd.read_json("/content/english_wsd_dataset.json").head(5)

           0                                                  1
0  d000.s000  [[long, [bn:00106124a]], [been, [bn:00083181v]...
1  d000.s001  [[permitted, [bn:00082536v]], [become, [bn:000...
2  d000.s002  [[effort, [bn:00007011n]], [make, [bn:00087106...
3  d000.s003  [[measure, [bn:00082720v]], [reduced, [bn:0010...
4  d000.s004  [[set, [bn:00086468v]], [specific, [bn:0011100...

#### Conversion en pandas DataFrame

In [15]:
def export_to_dataframe(sentences_with_annotations, output_path):
    """
    Exporte les données des phrases avec annotations dans un fichier CSV.

    :param sentences_with_annotations: Liste contenant des tuples (ID de phrase, annotations).
    :param output_path: Le chemin du fichier de sortie pour le fichier CSV.
    """
    data = []

    for sentence_data in sentences_with_annotations:
        sentence_id = sentence_data[0]  # L'ID de la phrase se trouve à l'index 0
        for annotation in sentence_data[1]:  # Les annotations sont à l'index 1
            word = annotation[0]  # Le mot est à l'index 0 de l'annotation
            sense_id = ', '.join(annotation[1])  # Les sens sont à l'index 1 et doivent être joints par une virgule
            data.append([sentence_id, word, sense_id])

    df = pd.DataFrame(data, columns=['sentence', 'word', 'sense'])
    df.to_csv(output_path, index=False, encoding='utf-8')
    print(f"Les données ont été exportées en CSV vers {output_path}")

In [16]:
output_path_csv = r"C:\Users\pc\Downloads\BIBDA\S3\Analyse de Sentiments et Text Mining\english-data\english_wsd_dataset.csv"
export_to_dataframe(annotations, output_path_csv)

Les données ont été exportées en CSV vers C:\Users\pc\Downloads\BIBDA\S3\Analyse de Sentiments et Text Mining\english-data\english_wsd_dataset.csv

In [17]:
from google.colab import files

uploaded = files.upload()  # Cette commande ouvrira une boîte de dialogue pour télécharger vos fichiers

Saving english_wsd_dataset.csv to english_wsd_dataset.csv

In [18]:
df = pd.read_csv("/content/english_wsd_dataset.csv")
df.head(5)

    sentence        word         sense
0  d000.s000        long  bn:00106124a
1  d000.s000        been  bn:00083181v
2  d000.s000    reviewed  bn:00092618v
3  d000.s000  objectives  bn:00002179n
4  d000.s000     benefit  bn:00009904n

# Vérification des valeurs manquantes

In [19]:
import re
# Vérification des valeurs manquantes
missing_values = df.isnull().sum()

# Vérification des doublons
duplicates = df.duplicated().sum()

In [20]:
# Vérification du format des Sense IDs
def is_valid_sense_id(sense_id):
    pattern = r'^bn:\d{8}[a-z]$'
    return bool(re.match(pattern, sense_id))

invalid_sense_ids = df[~df['sense'].apply(is_valid_sense_id)]

In [21]:
# Résultats
print("Résumé des vérifications :\n")
print(f"Valeurs manquantes par colonne :\n{missing_values}\n")
print(f"Nombre de doublons : {duplicates}\n")
if not invalid_sense_ids.empty:
    print(f"Sense IDs invalides :\n{invalid_sense_ids}\n")
else:
    print("Tous les Sense IDs sont valides.\n")

Résumé des vérifications :

Valeurs manquantes par colonne :
sentence    0
word        1
sense       0
dtype: int64

Nombre de doublons : 5621

Sense IDs invalides :
         sentence      word                       sense
72      d000.s010   service  bn:00070653n, bn:00070652n
371     d000.s046    public  bn:00109212a, bn:00109211a
1102    d001.s006     break  bn:00083902v, bn:00083904v
1159    d001.s016  handling  bn:00084527v, bn:00087116v
1196    d001.s023     cause  bn:00016845n, bn:00016850n
...           ...       ...                         ...
222803  d339.s009    caring  bn:00084527v, bn:00084524v
223324  d340.s122       lay  bn:00090322v, bn:00090321v
224476  d345.s107    called  bn:00084385v, bn:00084386v
224498  d345.s116      call  bn:00084385v, bn:00084386v
224618  d346.s042      show  bn:00083245v, bn:00086557v

[656 rows x 3 columns]

In [23]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.46.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.16.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.26.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2024.9.11)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.20.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.5)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.66.6)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (2024.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2024.8.30)

# Téléchargement du modèle préentraîné

In [22]:
NUM_SENSES = len(df['sense'].unique()) # correspond au nombre total d’étiquettes (Sense IDs) qu'on veux prédire.
print(f"Nombre unique de Sense IDs : {NUM_SENSES}")

Nombre unique de Sense IDs : 26326

In [23]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

#NUM_SENSES = 50 # correspond au nombre total d’étiquettes (Sense IDs) qu'on veux prédire.

# Charger un modèle préentraîné comme xlmr-base
model_name = "xlm-roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=NUM_SENSES)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at xlm-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

# Préparer les données

In [24]:
# Créez une correspondance entre chaque Sense ID et un entier unique
sense_mapping = {sense: idx for idx, sense in enumerate(df['sense'].unique())}

# Ajoutez une nouvelle colonne 'sense_id' dans le DataFrame
df['sense_id'] = df['sense'].map(sense_mapping) # La colonne sense_id doit associer chaque Sense ID (comme bn:00106124a) à un entier unique

# Vérifiez que la colonne a été correctement ajoutée
print(df.head(15))

     sentence        word         sense  sense_id
0   d000.s000        long  bn:00106124a         0
1   d000.s000        been  bn:00083181v         1
2   d000.s000    reviewed  bn:00092618v         2
3   d000.s000  objectives  bn:00002179n         3
4   d000.s000     benefit  bn:00009904n         4
5   d000.s000     service  bn:00070654n         5
6   d000.s000     program  bn:00064646n         6
7   d000.s001   permitted  bn:00082536v         7
8   d000.s001      become  bn:00083294v         8
9   d000.s001    giveaway  bn:00040564n         9
10  d000.s001     program  bn:00064646n         6
11  d000.s001      rather  bn:00115972r        10
12  d000.s001         has  bn:00088078v        11
13  d000.s001        goal  bn:00030721n        12
14  d000.s001    improved  bn:00104710a        13

In [25]:
from sklearn.model_selection import train_test_split
import torch
from torch.utils.data import Dataset, DataLoader

# Fractionner les données en train/test
#train_df, val_df = train_test_split(df, test_size=0.2, random_state=42)

In [26]:
class WSDDataset(Dataset):
    def __init__(self, dataframe, tokenizer, max_len):
        self.dataframe = dataframe
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, index):
        row = self.dataframe.iloc[index]
        inputs = self.tokenizer(
            row["sentence"],  # La phrase entière
            row["word"],      # Le mot cible
            padding="max_length",
            truncation=True,
            max_length=self.max_len,
            return_tensors="pt"
        )
        label = torch.tensor(row["sense_id"])  # Associe chaque Sense ID à un entier
        return {
            "input_ids": inputs["input_ids"].squeeze(0),
            "attention_mask": inputs["attention_mask"].squeeze(0),
            "labels": label,
        }

In [27]:
# Hyperparamètres
MAX_LEN = 128
BATCH_SIZE = 16

# Hyperparamètres ajustés
#MAX_LEN = 64  # Réduction de la longueur maximale des séquences
#BATCH_SIZE = 8  # Réduction de la taille des lots
#LEARNING_RATE = 5e-5  # Standard pour les Transformers
#EPOCHS = 2  # Moins d'époques pour économiser du temps et des ressources

In [28]:
from google.colab import files

uploaded = files.upload()  # Cette commande ouvrira une boîte de dialogue pour télécharger vos fichiers

Saving dev-en.data.xml to dev-en.data.xml
Saving dev-en.gold.key.txt to dev-en.gold.key.txt

In [30]:
# Charger et parser les données
train_sentences = df #parse_data('/content/semcor_en.data.xml')  # Ton fichier d'entraînement
val_sentences = parse_data('/content/dev-en.data.xml')
val_sentences_gold = parse_gold_keys('/content/dev-en.gold.key.txt')  # Fichier de validation (s'il existe)
print(train_sentences[:5])
print("\n")
print(val_sentences[:5])
#print(val_sentences[:5])
print(list(val_sentences_gold.items())[:5])

    sentence        word         sense  sense_id
0  d000.s000        long  bn:00106124a         0
1  d000.s000        been  bn:00083181v         1
2  d000.s000    reviewed  bn:00092618v         2
3  d000.s000  objectives  bn:00002179n         3
4  d000.s000     benefit  bn:00009904n         4


['referred research reported', 'comments implied discovered cause found', 'made statement', 'become', 'causes understood']
[('d000.s000.t000', ['bn:00082412v']), ('d000.s000.t001', ['bn:00067280n']), ('d000.s000.t002', ['bn:00092823v']), ('d000.s001.t000', ['bn:00020977n']), ('d000.s001.t001', ['bn:00085636v'])]

In [31]:
# Associer annotations
annotations = associate_annotations("/content/dev-en.data.xml", val_sentences_gold)

# Afficher les 5 premières annotations
for sentence_id, annotated_words in annotations[:5]:
    print(f"Sentence ID: {sentence_id}")
    for word, sense_id in annotated_words:
        print(f"  Word: {word}, Sense ID: {sense_id}")

Sentence ID: d000.s000
  Word: referred, Sense ID: ['bn:00082412v']
  Word: research, Sense ID: ['bn:00067280n']
  Word: reported, Sense ID: ['bn:00092823v']
Sentence ID: d000.s001
  Word: comments, Sense ID: ['bn:00020977n']
  Word: implied, Sense ID: ['bn:00085636v']
  Word: discovered, Sense ID: ['bn:00086933v']
  Word: cause, Sense ID: ['bn:00016850n']
  Word: found, Sense ID: ['bn:00086708v']
Sentence ID: d000.s002
  Word: made, Sense ID: ['bn:00090557v']
  Word: statement, Sense ID: ['bn:00001768n']
Sentence ID: d000.s003
  Word: become, Sense ID: ['bn:00083293v']
Sentence ID: d000.s004
  Word: causes, Sense ID: ['bn:00016850n']
  Word: understood, Sense ID: ['bn:00095375v']

In [32]:
print(len(val_sentences))
print(len(annotations))

135
135

In [33]:
for i in range(5):
    print(f"Phrase : {val_sentences[i]}")
    print(f"Annotations : {annotations[i]}")

Phrase : referred research reported
Annotations : ('d000.s000', [('referred', ['bn:00082412v']), ('research', ['bn:00067280n']), ('reported', ['bn:00092823v'])])
Phrase : comments implied discovered cause found
Annotations : ('d000.s001', [('comments', ['bn:00020977n']), ('implied', ['bn:00085636v']), ('discovered', ['bn:00086933v']), ('cause', ['bn:00016850n']), ('found', ['bn:00086708v'])])
Phrase : made statement
Annotations : ('d000.s002', [('made', ['bn:00090557v']), ('statement', ['bn:00001768n'])])
Phrase : become
Annotations : ('d000.s003', [('become', ['bn:00083293v'])])
Phrase : causes understood
Annotations : ('d000.s004', [('causes', ['bn:00016850n']), ('understood', ['bn:00095375v'])])

In [34]:
output_path_dev_csv = r"C:\Users\pc\Downloads\BIBDA\S3\Analyse de Sentiments et Text Mining\english-data\dev_wsd_dataset.csv"
#export_to_dataframe(annotations, output_path_dev_csv)
export_to_dataframe(annotations, "/content/dev_wsd_dataset.csv")

Les données ont été exportées en CSV vers /content/dev_wsd_dataset.csv

In [35]:
dev = pd.read_csv("/content/dev_wsd_dataset.csv")
dev.head(10)

    sentence        word         sense
0  d000.s000    referred  bn:00082412v
1  d000.s000    research  bn:00067280n
2  d000.s000    reported  bn:00092823v
3  d000.s001    comments  bn:00020977n
4  d000.s001     implied  bn:00085636v
5  d000.s001  discovered  bn:00086933v
6  d000.s001       cause  bn:00016850n
7  d000.s001       found  bn:00086708v
8  d000.s002        made  bn:00090557v
9  d000.s002   statement  bn:00001768n

In [36]:
train_sentences.head(10)

    sentence        word         sense  sense_id
0  d000.s000        long  bn:00106124a         0
1  d000.s000        been  bn:00083181v         1
2  d000.s000    reviewed  bn:00092618v         2
3  d000.s000  objectives  bn:00002179n         3
4  d000.s000     benefit  bn:00009904n         4
5  d000.s000     service  bn:00070654n         5
6  d000.s000     program  bn:00064646n         6
7  d000.s001   permitted  bn:00082536v         7
8  d000.s001      become  bn:00083294v         8
9  d000.s001    giveaway  bn:00040564n         9

In [37]:
# Créez une correspondance entre chaque Sense ID et un entier unique
dev_sense_mapping = {sense: idx for idx, sense in enumerate(df['sense'].unique())}

# Ajoutez une nouvelle colonne 'sense_id' dans le DataFrame
dev['sense_id'] = dev['sense'].map(dev_sense_mapping) # La colonne sense_id doit associer chaque Sense ID (comme bn:00106124a) à un entier unique

# Vérifiez que la colonne a été correctement ajoutée
print(dev.head(15))

     sentence        word         sense  sense_id
0   d000.s000    referred  bn:00082412v     883.0
1   d000.s000    research  bn:00067280n    2874.0
2   d000.s000    reported  bn:00092823v    2831.0
3   d000.s001    comments  bn:00020977n    2879.0
4   d000.s001     implied  bn:00085636v    8924.0
5   d000.s001  discovered  bn:00086933v    3246.0
6   d000.s001       cause  bn:00016850n    2966.0
7   d000.s001       found  bn:00086708v     445.0
8   d000.s002        made  bn:00090557v   25174.0
9   d000.s002   statement  bn:00001768n   22373.0
10  d000.s003      become  bn:00083293v     931.0
11  d000.s004      causes  bn:00016850n    2966.0
12  d000.s004  understood  bn:00095375v      94.0
13  d000.s005     quoting  bn:00085008v       NaN
14  d000.s005  emphasized  bn:00082195v     380.0

In [39]:
# Convertir en DataFrame
#train_df = pd.DataFrame(train_sentences, columns=["sentence", "word", "sense_id"])
#val_df = pd.DataFrame(dev, columns=["sentence", "word", "sense_id"])

In [38]:
# Créer les datasets
train_dataset = WSDDataset(train_sentences, tokenizer, max_len=MAX_LEN)
val_dataset = WSDDataset(dev, tokenizer, max_len=MAX_LEN)

In [40]:
# Configurer les DataLoaders
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE)

In [41]:
for batch in train_loader:
    print("input_ids shape :", batch["input_ids"].shape)  # (batch_size, max_len)
    print("attention_mask shape :", batch["attention_mask"].shape)  # (batch_size, max_len)
    print("labels shape :", batch["labels"].shape)  # (batch_size,)
    break

input_ids shape : torch.Size([16, 128])
attention_mask shape : torch.Size([16, 128])
labels shape : torch.Size([16])

In [52]:
import torch
print(torch.cuda.is_available())  # Doit retourner True si le GPU est activé
print(torch.cuda.get_device_name(0))  # Affiche le nom du GPU

True
Tesla T4

In [53]:
#device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cuda

In [ ]:
for batch in train_loader:
    input_ids = batch["input_ids"].to(device)
    attention_mask = batch["attention_mask"].to(device)
    labels = batch["labels"].to(device)

    outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
    print("Loss :", outputs.loss.item())
    break

# Entraîner le modèle

> # *Test avec un petit sous-ensemble de données avant le lancer l'entraînement complet.*

In [54]:
# Réduire la taille des données
train_df_small = train_sentences.sample(n=100, random_state=42)  # Par exemple, 100 exemples
val_df_small = dev.sample(n=20, random_state=42)       # Par exemple, 20 exemples

In [55]:
# Générer des datasets pour l'échantillon
train_dataset_small = WSDDataset(train_df_small, tokenizer, max_len=MAX_LEN)
val_dataset_small = WSDDataset(val_df_small, tokenizer, max_len=MAX_LEN)

# Générer des dataloaders pour l'échantillon
train_loader_small = DataLoader(train_dataset_small, batch_size=16, shuffle=True)
val_loader_small = DataLoader(val_dataset_small, batch_size=16, shuffle=False)

In [58]:
from transformers import AdamW
from torch.nn import CrossEntropyLoss
from tqdm import tqdm


# Configuration du modèle et des tenseurs sur le bon appareil
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)  # S'assurer que le modèle est sur le bon appareil

# Optimiseur et paramètres
optimizer = AdamW(model.parameters(), lr=2e-5)
criterion = CrossEntropyLoss()

EPOCHS = 100

# Boucle d'entraînement
for epoch in range(EPOCHS):
    model.train()
    total_loss = 0

    for batch in tqdm(train_loader_small, desc=f"Epoch {epoch + 1}/{EPOCHS}"):
        # Transférer les données sur le bon appareil
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device)

        optimizer.zero_grad()

        # Exécuter le modèle et calculer la perte
        outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)

        loss = outputs.loss
        total_loss += loss.item()

        # Rétropropagation et mise à jour des paramètres
        loss.backward()
        optimizer.step()

    # Afficher la perte moyenne pour cette époque
    avg_loss = total_loss / len(train_loader_small)
    print(f"Epoch {epoch + 1}/{EPOCHS}, Loss: {avg_loss:.4f}")

Epoch 1/100: 100%|██████████| 7/7 [00:02<00:00,  2.94it/s]

Epoch 1/100, Loss: 10.1364

Epoch 2/100: 100%|██████████| 7/7 [00:02<00:00,  3.04it/s]

Epoch 2/100, Loss: 10.1305

Epoch 3/100: 100%|██████████| 7/7 [00:02<00:00,  3.04it/s]

Epoch 3/100, Loss: 10.0789

Epoch 4/100: 100%|██████████| 7/7 [00:02<00:00,  3.05it/s]

Epoch 4/100, Loss: 10.0166

Epoch 5/100: 100%|██████████| 7/7 [00:02<00:00,  3.01it/s]

Epoch 5/100, Loss: 9.9905

Epoch 6/100: 100%|██████████| 7/7 [00:02<00:00,  3.02it/s]

Epoch 6/100, Loss: 9.9310

Epoch 7/100: 100%|██████████| 7/7 [00:02<00:00,  2.96it/s]

Epoch 7/100, Loss: 9.8007

Epoch 8/100: 100%|██████████| 7/7 [00:02<00:00,  3.01it/s]

Epoch 8/100, Loss: 9.7832

Epoch 9/100: 100%|██████████| 7/7 [00:02<00:00,  3.01it/s]

Epoch 9/100, Loss: 9.6618

Epoch 10/100: 100%|██████████| 7/7 [00:02<00:00,  3.01it/s]

Epoch 10/100, Loss: 9.6472

Epoch 11/100: 100%|██████████| 7/7 [00:02<00:00,  3.01it/s]

Epoch 11/100, Loss: 9.5056

Epoch 12/100: 100%|██████████| 7/7 [00:02<00:00,  2.98it/s]

Epoch 12/100, Loss: 9.4324

Epoch 13/100: 100%|██████████| 7/7 [00:02<00:00,  3.00it/s]

Epoch 13/100, Loss: 9.3452

Epoch 14/100: 100%|██████████| 7/7 [00:02<00:00,  2.99it/s]

Epoch 14/100, Loss: 9.1686

Epoch 15/100: 100%|██████████| 7/7 [00:02<00:00,  2.98it/s]

Epoch 15/100, Loss: 9.1185

Epoch 16/100: 100%|██████████| 7/7 [00:02<00:00,  2.97it/s]

Epoch 16/100, Loss: 8.9749

Epoch 17/100: 100%|██████████| 7/7 [00:02<00:00,  2.96it/s]

Epoch 17/100, Loss: 8.9157

Epoch 18/100: 100%|██████████| 7/7 [00:02<00:00,  2.98it/s]

Epoch 18/100, Loss: 8.7452

Epoch 19/100: 100%|██████████| 7/7 [00:02<00:00,  2.97it/s]

Epoch 19/100, Loss: 8.6650

Epoch 20/100: 100%|██████████| 7/7 [00:02<00:00,  2.96it/s]

Epoch 20/100, Loss: 8.5286

Epoch 21/100: 100%|██████████| 7/7 [00:02<00:00,  2.98it/s]

Epoch 21/100, Loss: 8.3524

Epoch 22/100: 100%|██████████| 7/7 [00:02<00:00,  2.96it/s]

Epoch 22/100, Loss: 8.2367

Epoch 23/100: 100%|██████████| 7/7 [00:02<00:00,  2.95it/s]

Epoch 23/100, Loss: 8.0528

Epoch 24/100: 100%|██████████| 7/7 [00:02<00:00,  2.97it/s]

Epoch 24/100, Loss: 7.9473

Epoch 25/100: 100%|██████████| 7/7 [00:02<00:00,  2.94it/s]

Epoch 25/100, Loss: 7.7147

Epoch 26/100: 100%|██████████| 7/7 [00:02<00:00,  2.95it/s]

Epoch 26/100, Loss: 7.6793

Epoch 27/100: 100%|██████████| 7/7 [00:02<00:00,  2.94it/s]

Epoch 27/100, Loss: 7.4607

Epoch 28/100: 100%|██████████| 7/7 [00:02<00:00,  2.95it/s]

Epoch 28/100, Loss: 7.3378

Epoch 29/100: 100%|██████████| 7/7 [00:02<00:00,  2.93it/s]

Epoch 29/100, Loss: 7.1746

Epoch 30/100: 100%|██████████| 7/7 [00:02<00:00,  2.92it/s]

Epoch 30/100, Loss: 6.9923

Epoch 31/100: 100%|██████████| 7/7 [00:02<00:00,  2.92it/s]

Epoch 31/100, Loss: 6.7653

Epoch 32/100: 100%|██████████| 7/7 [00:02<00:00,  2.91it/s]

Epoch 32/100, Loss: 6.6935

Epoch 33/100: 100%|██████████| 7/7 [00:02<00:00,  2.91it/s]

Epoch 33/100, Loss: 6.5439

Epoch 34/100: 100%|██████████| 7/7 [00:02<00:00,  2.90it/s]

Epoch 34/100, Loss: 6.3865

Epoch 35/100: 100%|██████████| 7/7 [00:02<00:00,  2.91it/s]

Epoch 35/100, Loss: 6.1978

Epoch 36/100: 100%|██████████| 7/7 [00:02<00:00,  2.92it/s]

Epoch 36/100, Loss: 6.1146

Epoch 37/100: 100%|██████████| 7/7 [00:02<00:00,  2.93it/s]

Epoch 37/100, Loss: 5.9342

Epoch 38/100: 100%|██████████| 7/7 [00:02<00:00,  2.90it/s]

Epoch 38/100, Loss: 5.8469

Epoch 39/100: 100%|██████████| 7/7 [00:02<00:00,  2.89it/s]

Epoch 39/100, Loss: 5.6890

Epoch 40/100: 100%|██████████| 7/7 [00:02<00:00,  2.91it/s]

Epoch 40/100, Loss: 5.6770

Epoch 41/100: 100%|██████████| 7/7 [00:02<00:00,  2.87it/s]

Epoch 41/100, Loss: 5.5237

Epoch 42/100: 100%|██████████| 7/7 [00:02<00:00,  2.89it/s]

Epoch 42/100, Loss: 5.4582

Epoch 43/100: 100%|██████████| 7/7 [00:02<00:00,  2.90it/s]

Epoch 43/100, Loss: 5.3701

Epoch 44/100: 100%|██████████| 7/7 [00:02<00:00,  2.89it/s]

Epoch 44/100, Loss: 5.2693

Epoch 45/100: 100%|██████████| 7/7 [00:02<00:00,  2.87it/s]

Epoch 45/100, Loss: 5.2257

Epoch 46/100: 100%|██████████| 7/7 [00:02<00:00,  2.88it/s]

Epoch 46/100, Loss: 5.1711

Epoch 47/100: 100%|██████████| 7/7 [00:02<00:00,  2.88it/s]

Epoch 47/100, Loss: 5.0900

Epoch 48/100: 100%|██████████| 7/7 [00:02<00:00,  2.89it/s]

Epoch 48/100, Loss: 5.1070

Epoch 49/100: 100%|██████████| 7/7 [00:02<00:00,  2.87it/s]

Epoch 49/100, Loss: 5.0043

Epoch 50/100: 100%|██████████| 7/7 [00:02<00:00,  2.86it/s]

Epoch 50/100, Loss: 4.9975

Epoch 51/100: 100%|██████████| 7/7 [00:02<00:00,  2.86it/s]

Epoch 51/100, Loss: 4.9733

Epoch 52/100: 100%|██████████| 7/7 [00:02<00:00,  2.86it/s]

Epoch 52/100, Loss: 4.9493

Epoch 53/100: 100%|██████████| 7/7 [00:02<00:00,  2.87it/s]

Epoch 53/100, Loss: 4.8645

Epoch 54/100: 100%|██████████| 7/7 [00:02<00:00,  2.85it/s]

Epoch 54/100, Loss: 4.8834

Epoch 55/100: 100%|██████████| 7/7 [00:02<00:00,  2.86it/s]

Epoch 55/100, Loss: 4.8343

Epoch 56/100: 100%|██████████| 7/7 [00:02<00:00,  2.85it/s]

Epoch 56/100, Loss: 4.8361

Epoch 57/100: 100%|██████████| 7/7 [00:02<00:00,  2.86it/s]

Epoch 57/100, Loss: 4.7895

Epoch 58/100: 100%|██████████| 7/7 [00:02<00:00,  2.85it/s]

Epoch 58/100, Loss: 4.7499

Epoch 59/100: 100%|██████████| 7/7 [00:02<00:00,  2.84it/s]

Epoch 59/100, Loss: 4.7230

Epoch 60/100: 100%|██████████| 7/7 [00:02<00:00,  2.84it/s]

Epoch 60/100, Loss: 4.7578

Epoch 61/100: 100%|██████████| 7/7 [00:02<00:00,  2.86it/s]

Epoch 61/100, Loss: 4.7344

Epoch 62/100: 100%|██████████| 7/7 [00:02<00:00,  2.82it/s]

Epoch 62/100, Loss: 4.6887

Epoch 63/100: 100%|██████████| 7/7 [00:02<00:00,  2.85it/s]

Epoch 63/100, Loss: 4.7256

Epoch 64/100: 100%|██████████| 7/7 [00:02<00:00,  2.84it/s]

Epoch 64/100, Loss: 4.6896

Epoch 65/100: 100%|██████████| 7/7 [00:02<00:00,  2.83it/s]

Epoch 65/100, Loss: 4.6883

Epoch 66/100: 100%|██████████| 7/7 [00:02<00:00,  2.84it/s]

Epoch 66/100, Loss: 4.6544

Epoch 67/100: 100%|██████████| 7/7 [00:02<00:00,  2.84it/s]

Epoch 67/100, Loss: 4.6387

Epoch 68/100: 100%|██████████| 7/7 [00:02<00:00,  2.83it/s]

Epoch 68/100, Loss: 4.6450

Epoch 69/100: 100%|██████████| 7/7 [00:02<00:00,  2.84it/s]

Epoch 69/100, Loss: 4.5995

Epoch 70/100: 100%|██████████| 7/7 [00:02<00:00,  2.84it/s]

Epoch 70/100, Loss: 4.5891

Epoch 71/100: 100%|██████████| 7/7 [00:02<00:00,  2.82it/s]

Epoch 71/100, Loss: 4.5804

Epoch 72/100: 100%|██████████| 7/7 [00:02<00:00,  2.82it/s]

Epoch 72/100, Loss: 4.5687

Epoch 73/100: 100%|██████████| 7/7 [00:02<00:00,  2.82it/s]

Epoch 73/100, Loss: 4.5194

Epoch 74/100: 100%|██████████| 7/7 [00:02<00:00,  2.83it/s]

Epoch 74/100, Loss: 4.4460

Epoch 75/100: 100%|██████████| 7/7 [00:02<00:00,  2.83it/s]

Epoch 75/100, Loss: 4.5344

Epoch 76/100: 100%|██████████| 7/7 [00:02<00:00,  2.82it/s]

Epoch 76/100, Loss: 4.4295

Epoch 77/100: 100%|██████████| 7/7 [00:02<00:00,  2.82it/s]

Epoch 77/100, Loss: 4.4361

Epoch 78/100: 100%|██████████| 7/7 [00:02<00:00,  2.82it/s]

Epoch 78/100, Loss: 4.4576

Epoch 79/100: 100%|██████████| 7/7 [00:02<00:00,  2.81it/s]

Epoch 79/100, Loss: 4.3810

Epoch 80/100: 100%|██████████| 7/7 [00:02<00:00,  2.82it/s]

Epoch 80/100, Loss: 4.3856

Epoch 81/100: 100%|██████████| 7/7 [00:02<00:00,  2.82it/s]

Epoch 81/100, Loss: 4.3704

Epoch 82/100: 100%|██████████| 7/7 [00:02<00:00,  2.81it/s]

Epoch 82/100, Loss: 4.3592

Epoch 83/100: 100%|██████████| 7/7 [00:02<00:00,  2.82it/s]

Epoch 83/100, Loss: 4.2485

Epoch 84/100: 100%|██████████| 7/7 [00:02<00:00,  2.81it/s]

Epoch 84/100, Loss: 4.2763

Epoch 85/100: 100%|██████████| 7/7 [00:02<00:00,  2.80it/s]

Epoch 85/100, Loss: 4.2240

Epoch 86/100: 100%|██████████| 7/7 [00:02<00:00,  2.81it/s]

Epoch 86/100, Loss: 4.1933

Epoch 87/100: 100%|██████████| 7/7 [00:02<00:00,  2.81it/s]

Epoch 87/100, Loss: 4.1554

Epoch 88/100: 100%|██████████| 7/7 [00:02<00:00,  2.80it/s]

Epoch 88/100, Loss: 4.1481

Epoch 89/100: 100%|██████████| 7/7 [00:02<00:00,  2.80it/s]

Epoch 89/100, Loss: 4.0477

Epoch 90/100: 100%|██████████| 7/7 [00:02<00:00,  2.80it/s]

Epoch 90/100, Loss: 4.0144

Epoch 91/100: 100%|██████████| 7/7 [00:02<00:00,  2.80it/s]

Epoch 91/100, Loss: 3.9798

Epoch 92/100: 100%|██████████| 7/7 [00:02<00:00,  2.81it/s]

Epoch 92/100, Loss: 3.9410

Epoch 93/100: 100%|██████████| 7/7 [00:02<00:00,  2.79it/s]

Epoch 93/100, Loss: 3.9231

Epoch 94/100: 100%|██████████| 7/7 [00:02<00:00,  2.80it/s]

Epoch 94/100, Loss: 3.9133

Epoch 95/100: 100%|██████████| 7/7 [00:02<00:00,  2.80it/s]

Epoch 95/100, Loss: 3.8586

Epoch 96/100: 100%|██████████| 7/7 [00:02<00:00,  2.80it/s]

Epoch 96/100, Loss: 3.7562

Epoch 97/100: 100%|██████████| 7/7 [00:02<00:00,  2.80it/s]

Epoch 97/100, Loss: 3.7612

Epoch 98/100: 100%|██████████| 7/7 [00:02<00:00,  2.80it/s]

Epoch 98/100, Loss: 3.6350

Epoch 99/100: 100%|██████████| 7/7 [00:02<00:00,  2.80it/s]

Epoch 99/100, Loss: 3.6876

Epoch 100/100: 100%|██████████| 7/7 [00:02<00:00,  2.81it/s]

Epoch 100/100, Loss: 3.5631

In [59]:
# Sauvegarder le modèle fine-tuné sur collab
model.save_pretrained("./final_model_test")
tokenizer.save_pretrained("./final_model_test")

('./final_model_test/tokenizer_config.json',
 './final_model_test/special_tokens_map.json',
 './final_model_test/sentencepiece.bpe.model',
 './final_model_test/added_tokens.json',
 './final_model_test/tokenizer.json')

In [62]:
import os

chemin = r"C:\Users\pc\Downloads\BIBDA\S3\Analyse de Sentiments et Text Mining\mon_model\final_model_test"

# Vérifiez si le chemin existe, sinon créez-le
if not os.path.exists(chemin):
    os.makedirs(chemin)

# Sauvegarder le modèle
model.save_pretrained(chemin)
tokenizer.save_pretrained(chemin)

('C:\\Users\\pc\\Downloads\\BIBDA\\S3\\Analyse de Sentiments et Text Mining\\mon_model\\final_model_test/tokenizer_config.json',
 'C:\\Users\\pc\\Downloads\\BIBDA\\S3\\Analyse de Sentiments et Text Mining\\mon_model\\final_model_test/special_tokens_map.json',
 'C:\\Users\\pc\\Downloads\\BIBDA\\S3\\Analyse de Sentiments et Text Mining\\mon_model\\final_model_test/sentencepiece.bpe.model',
 'C:\\Users\\pc\\Downloads\\BIBDA\\S3\\Analyse de Sentiments et Text Mining\\mon_model\\final_model_test/added_tokens.json',
 'C:\\Users\\pc\\Downloads\\BIBDA\\S3\\Analyse de Sentiments et Text Mining\\mon_model\\final_model_test/tokenizer.json')

In [65]:
# Préparer les données d'évaluation
val_loader_small = torch.utils.data.DataLoader(
    val_dataset_small, batch_size=16, shuffle=False
)

In [66]:
from tqdm import tqdm
from sklearn.metrics import accuracy_score

def evaluate_model(model, val_loader, device):
    model.eval()
    predictions, true_labels = [], []

    with torch.no_grad():
        for batch in tqdm(val_loader, desc="Évaluation"):
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            # Obtenir les prédictions
            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            logits = outputs.logits
            preds = torch.argmax(logits, dim=1).cpu().numpy()

            # Sauvegarder les prédictions et labels réels
            predictions.extend(preds)
            true_labels.extend(labels.cpu().numpy())

    # Calculer l'accuracy
    accuracy = accuracy_score(true_labels, predictions)
    print(f"Accuracy : {accuracy:.4f}")

    return predictions, true_labels

In [68]:
for batch in val_loader_small:
    print(batch["labels"])
    if torch.isnan(batch["labels"]).any():
        print("NaN found in labels!")

tensor([   nan,   277.,  3941.,   931., 18558.,  1955.,  8048.,  1661., 16477.,
         4222.,  3424.,   830.,   692.,  7039.,  6585.,   639.],
       dtype=torch.float64)
NaN found in labels!
tensor([2.4220e+03, 6.0000e+00, 2.1681e+04, 9.3000e+01], dtype=torch.float64)

In [69]:
# Vérifier et filtrer les données avec NaN dans les labels
filtered_data = [
    example
    for example in val_dataset_small
    if not torch.isnan(torch.tensor(example["labels"]))
]

# Recréer le DataLoader après nettoyage
val_loader_small = torch.utils.data.DataLoader(
    filtered_data, batch_size=16, shuffle=False
)

<ipython-input-69-958fe02ba43f>:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  if not torch.isnan(torch.tensor(example["labels"]))

In [70]:
predictions, true_labels = evaluate_model(model, val_loader_small, device)

Évaluation: 100%|██████████| 2/2 [00:00<00:00,  9.90it/s]

Accuracy : 0.0526

In [71]:
# Exemple de phrase à tester
example_sentence = "The service was excellent and very quick."

# Tokenization
inputs = tokenizer(
    example_sentence,
    return_tensors="pt",
    padding=True,
    truncation=True,
    max_length=128
).to(device)

# Prédiction
model.eval()
with torch.no_grad():
    outputs = model(**inputs)
    logits = outputs.logits
    prediction = torch.argmax(logits, dim=1).item()

print(f"Prediction ID : {prediction}")

Prediction ID : 175

### Vérifier les prédictions

In [72]:
for pred, true in zip(predictions, true_labels):
    print(f"Prediction: {pred}, True Label: {true}")

Prediction: 731, True Label: 277.0
Prediction: 2852, True Label: 3941.0
Prediction: 639, True Label: 931.0
Prediction: 612, True Label: 18558.0
Prediction: 1838, True Label: 1955.0
Prediction: 731, True Label: 8048.0
Prediction: 639, True Label: 1661.0
Prediction: 639, True Label: 16477.0
Prediction: 1723, True Label: 4222.0
Prediction: 639, True Label: 3424.0
Prediction: 1838, True Label: 830.0
Prediction: 763, True Label: 692.0
Prediction: 2852, True Label: 7039.0
Prediction: 639, True Label: 6585.0
Prediction: 639, True Label: 639.0
Prediction: 763, True Label: 2422.0
Prediction: 763, True Label: 6.0
Prediction: 1723, True Label: 21681.0
Prediction: 639, True Label: 93.0

### Calculer d'autres métriques

In [73]:
from sklearn.metrics import classification_report

print(classification_report(true_labels, predictions))

              precision    recall  f1-score   support

         6.0       0.00      0.00      0.00         1
        93.0       0.00      0.00      0.00         1
       277.0       0.00      0.00      0.00         1
       612.0       0.00      0.00      0.00         0
       639.0       0.14      1.00      0.25         1
       692.0       0.00      0.00      0.00         1
       731.0       0.00      0.00      0.00         0
       763.0       0.00      0.00      0.00         0
       830.0       0.00      0.00      0.00         1
       931.0       0.00      0.00      0.00         1
      1661.0       0.00      0.00      0.00         1
      1723.0       0.00      0.00      0.00         0
      1838.0       0.00      0.00      0.00         0
      1955.0       0.00      0.00      0.00         1
      2422.0       0.00      0.00      0.00         1
      2852.0       0.00      0.00      0.00         0
      3424.0       0.00      0.00      0.00         1
      3941.0       0.00      0.00      0.00         1
      4222.0       0.00      0.00      0.00         1
      6585.0       0.00      0.00      0.00         1
      7039.0       0.00      0.00      0.00         1
      8048.0       0.00      0.00      0.00         1
     16477.0       0.00      0.00      0.00         1
     18558.0       0.00      0.00      0.00         1
     21681.0       0.00      0.00      0.00         1

    accuracy                           0.05        19
   macro avg       0.01      0.04      0.01        19
weighted avg       0.01      0.05      0.01        19

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

### Vérifier le déséquilibre des classes

In [74]:
import pandas as pd
from collections import Counter

label_counts = Counter(true_labels)
print(pd.DataFrame.from_dict(label_counts, orient='index', columns=['Count']))

         Count
277.0        1
3941.0       1
931.0        1
18558.0      1
1955.0       1
8048.0       1
1661.0       1
16477.0      1
4222.0       1
3424.0       1
830.0        1
692.0        1
7039.0       1
6585.0       1
639.0        1
2422.0       1
6.0          1
21681.0      1
93.0         1

### Analyser les prédictions incorrectes

In [80]:
incorrect = [
    (sentence, word, pred, true)
    for sentence, mot, pred, true in zip(sentences, word, predictions, true_labels)
    if pred != true
]
for entry in incorrect:
    print(f"Sentence: {entry[0]}, Word: {entry[1]}, Prediction: {entry[2]}, True: {entry[3]}")

Sentence: long been reviewed objectives benefit service program, Word: understood, Prediction: 731, True: 277.0
Sentence: permitted become giveaway program rather has goal improved employee morale consequently increased productivity, Word: understood, Prediction: 2852, True: 3941.0
Sentence: effort make assess results program, Word: understood, Prediction: 639, True: 931.0
Sentence: measure reduced absenteeism turnover accidents grievances improved quality output, Word: understood, Prediction: 612, True: 18558.0
Sentence: set specific objectives employee publication, Word: understood, Prediction: 1838, True: 1955.0
Sentence: reaching goals, Word: understood, Prediction: 731, True: 8048.0
Sentence: Is larger fancier really need, Word: understood, Prediction: 639, True: 1661.0
Sentence: using most economical printing methods paper, Word: understood, Prediction: 639, True: 16477.0
Sentence: Are other cheaper communications techniques substituted, Word: understood, Prediction: 1723, True: 4222.0
Sentence: attitude employee benefits encouraged excess free government work plant, Word: understood, Prediction: 639, True: 3424.0

> # *Fin de l'entrainement et evaluation pour le test sur le sous-ensemble*

# Entrainement complet